.\" generated with Ronn/v0.5
.\" http://github.com/rtomayko/ronn/
.
.TH "RONN" "1" "June 2010" "Ryan Tomayko" "Ronn Manual"
.
.SH "NAME"
\fBronn\fR \- build markdown\-based man pages
.
.SH "SYNOPSIS"
\fBronn\fR
.
.br
\fBronn\fR [\fIOPTIONS\fR] \fIFILE\fR...
.
.br
\fBronn\fR \-\-man \fIFILE\fR...
.
.SH "DESCRIPTION"
The \fBronn\fR utility converts ronn(5)\-formatted source files to roff and HTML
manpages.
.
.P
Under the first synopsis form \-\- with no \fIFILE\fR arguments \-\- \fBronn\fR acts as
simple filter, reading ronn source text on standard input and writing
roff(5)\-formatted text to standard output.
.
.P
Under the second synopsis form, \fBronn\fR builds HTML and roff output files based
on one or more input \fIFILE\fR names. The \fB\-\-roff\fR, \fB\-\-html\fR, and \fB\-\-fragment\fR
options specify which output files should be generated. Multiple format
arguments may be specified to generate multiple output files.
.
.P
Under the third synopsis form, \fBronn\fR converts one or more \fIFILE\fRs to roff
and displays on the current console as with man(1).
.
.SH "FILES"
The \fBronn\fR command expects input to be formatted as ronn(5) text.  Source
files are typically named '\fINAME\fR.\fISECTION\fR.ronn' (e.g., \fBhello.1.ronn\fR).
The \fINAME\fR and \fISECTION\fR should match the name and section defined in the \fIFILE\fR's heading.
.
.P
When building roff and/or HTML output files, destination filenames are
determined by taking the basename of the input \fIFILE\fR and adding the appropriate
file extension (or removing the file extension in the case of roff output).  For
example, executing \fBronn hello.1.ronn\fR generates a \fBhello.1\fR file with roff
output and a \fBhello.1.html\fR file with HTML output.
.
.SH "OPTIONS"
These options control whether output is written to file(s), to standard output,
or piped directly to a man viewer.
.
.TP
\fB\-\-pipe\fR
Write generated output to standard output instead of to filename based on
the input files. This is the default behavior when ronn source text is piped
in on standard input and no \fIFILE\fR arguments are provided.
.
.TP
\fB\-m\fR, \fB\-\-man\fR
Display \fIFILE\fRs as if man(1) were invoked on the roff output file. This
simulates default man behavior by piping the roff output through groff(1)
and the paging program specified by the \fBMANPAGER\fR environment variable.
.
.P
Format options control what files \fBronn\fR generates or the output format when the \fB\-\-pipe\fR argument is specified. When no format options are given, both \fB\-\-roff\fR
and \fB\-\-html\fR are assumed.
.
.TP
\fB\-r\fR, \fB\-\-roff\fR
Generate roff output. This is the default behavior when no \fIFILE\fRs are given
and ronn source text is read from standard input.
.
.TP
\fB\-5\fR, \fB\-\-html\fR
Generate output in HTML format.
.
.TP
\fB\-f\fR, \fB\-\-fragment\fR
Generate output in HTML format but only the document fragment, not the
header, title, or footer.
.
.P
All document attributes displayed in the header and footer areas of generated
content can be specified with these options:
.
.TP
\fB\-\-manual\fR=\fIMANUAL\fR
The name of the manual this man page belongs to; \fIMANUAL\fR is prominently
displayed top\-center in the header area.
.
.TP
\fB\-\-organization\fR=\fINAME\fR
The name of the group, organization, or individual responsible for
publishing the document; \fINAME\fR is displayed in the bottom\-left footer area.
.
.TP
\fB\-\-date\fR=\fIDATE\fR
The document's published date; \fIDATE\fR must be formatted \fBYYYY\-MM\-DD\fR and is
displayed in the bottom\-center footer area. The \fIFILE\fR mtime is used when no \fIDATE\fR is given, or the current time when no \fIFILE\fR is available.
.
.P
Miscellaneous options:
.
.IP "\(bu" 4
\fB\-w\fR, \fB\-\-warnings\fR
Show troff warnings on standard error when performing roff conversion. Most
often, warnings are the result of a bug in ronn's HTML to roff conversion
logic.
.
.IP "\(bu" 4
\fB\-W\fR:
Disable troff warnings. Warnings are disabled by default. This option can be
used to revert the effect of a previous \fB\-w\fR argument.
.
.IP "" 0
.
.SH "EXAMPLES"
Generate \fBroff(7)\fR output on stdout:
.
.IP "" 4
.
.nf

$ ronn < hello.1.ronn
.
.fi
.
.IP "" 0
.
.P
Build roff and HTML output files based on the input filename and view the roff
manpage using man(1):
.
.IP "" 4
.
.nf

$ ronn hello.1.ronn
roff: hello.1
html: hello.1.html
$ man ./hello.1
.
.fi
.
.IP "" 0
.
.P
Build only the HTML manpage:
.
.IP "" 4
.
.nf

$ ronn \-\-html test.1.ronn
html: hello.1.html
.
.fi
.
.IP "" 0
.
.P
Build only the roff manpage for all \fB.ronn\fR files in the current directory:
.
.IP "" 4
.
.nf

$ ronn \-\-roff *.ronn
roff: hello.1
roff: world.1
.
.fi
.
.IP "" 0
.
.P
View a ronn file in the same way as man(1) without building a roff file:
.
.IP "" 4
.
.nf

$ ronn \-m hello.1.ronn
.
.fi
.
.IP "" 0
.
.SH "ENVIRONMENT"
.
.TP
\fBMANPAGER\fR
The paging program used for man pages. This is typically set to
something like 'less \-is'.
.
.TP
\fBPAGER\fR
Used instead of \fBMANPAGER\fR when \fBMANPAGER\fR is not defined.
.
.SH "BUGS"
\fBRonn\fR is written in Ruby and depends on hpricot and rdiscount, extension
libraries that are non\-trivial to install on some systems. A more portable
version of this program would be welcome.
.
.SH "COPYRIGHT"
Ronn is Copyright (C) 2009 Ryan Tomayko <tomayko.com/about>
.
.SH "SEE ALSO"
ronn(5), markdown(7), manpages(5), man(1), roff(7), groff(1)
