.\" generated with Ronn/v0.6.42
.\" http://github.com/rtomayko/ronn/tree/0.6.6-36-gb67d494
.
.TH "RONN" "7" "June 2010" "0.6.6-36-gb67d494" "Ronn 0.6.42"
.
.SH "NAME"
\fBronn\fR \- the opposite of roff
.
.SH "DESCRIPTION"
Ronn is a text format and toolchain for creating UNIX manpages\. It converts markdown to standard UNIX roff manpages and formatted HTML manuals for the web\.
.
.P
The source format includes all of Markdown but has a more rigid structure and includes extensions that provide features commonly found in manpages (definition lists, link notation, etc\.)\. The ronn(5) manual page defines the format in detail\.
.
.SH "DOCUMENTATION"
The \fB\.ronn\fR files located under the \fBman/\fR directory show off a wide range of ronn capabilities and are the source of Ronn\'s own documentation\. The source files and generated HTML / roff output files are available at:
.
.IP "\(bu" 4
ronn(1) \fIhttp://rtomayko\.github\.com/ronn/ronn\.1\fR \- convert markdown files to manpages\.
.
.br
source file \fIhttp://github\.com/rtomayko/ronn/blob/master/man/ronn\.1\.ronn\fR, roff output \fIhttp://github\.com/rtomayko/ronn/blob/master/man/ronn\.1\fR
.
.IP "\(bu" 4
ronn(5) \fIhttp://rtomayko\.github\.com/ronn/ronn\.5\fR \- markdown\-based text format for authoring manpages
.
.br
source file \fIhttp://github\.com/rtomayko/ronn/blob/master/man/ronn\.5\.ronn\fR, roff output \fIhttp://github\.com/rtomayko/ronn/blob/master/man/ronn\.5\fR
.
.IP "" 0
.
.SH "INSTALL"
Install with Rubygems:
.
.IP "" 4
.
.nf

$ [sudo] gem install ronn
$ ronn \-\-help
.
.fi
.
.IP "" 0
.
.P
Or, clone the git repository:
.
.IP "" 4
.
.nf

$ git clone git://github\.com/rtomayko/ronn\.git
$ PATH=ronn/bin:$PATH
$ ronn \-\-help
.
.fi
.
.IP "" 0
.
.SH "BASIC USAGE"
Build roff and HTML output files for one or more input files:
.
.IP "" 4
.
.nf

$ ronn man/ronn\.5\.ronn
roff: man/ronn\.5
html: man/ronn\.5\.html
.
.fi
.
.IP "" 0
.
.P
View a roff manpage with man(1):
.
.IP "" 4
.
.nf

$ man man/ronn\.5
.
.fi
.
.IP "" 0
.
.P
Generate only a standalone HTML version of one or more files:
.
.IP "" 4
.
.nf

$ ronn \-\-html man/markdown\.5\.ronn
html: man/markdown\.5\.html
.
.fi
.
.IP "" 0
.
.P
Build roff versions of all ronn files in a directory:
.
.IP "" 4
.
.nf

$ ronn \-\-roff man/*\.ronn
.
.fi
.
.IP "" 0
.
.P
View a ronn file as if it were a manpage without building intermediate files:
.
.IP "" 4
.
.nf

$ ronn \-\-man man/markdown\.5\.ronn
.
.fi
.
.IP "" 0
.
.P
The ronn(1) \fIhttp://rtomayko\.github\.com/ronn/ronn\.1\fR manual page includes comprehensive documentation on \fBronn\fR command line options\.
.
.SH "ABOUT"
Some people say UNIX manual pages are a poor and outdated style of documentation\. I disagree:
.
.IP "\(bu" 4
Man pages follow a well defined structure that\'s immediately familiar\. This provides developers with a useful starting point when documenting new tools, libraries, and formats\.
.
.IP "\(bu" 4
Man pages get to the point\. Because they\'re written in an inverted style, with a SYNOPSIS section followed by additional detail, prose and references to other sources of information, man pages provide the best of both cheat sheet and reference style documentation\.
.
.IP "\(bu" 4
Man pages have extremely \-\- unbelievably \-\- limited text formatting capabilities\. You get a couple of headings, lists, bold, underline and no more\. This is a feature\.
.
.IP "\(bu" 4
Although two levels of section hierarchy are technically supported, most man pages use only a single level\. Unwieldy document hierarchies complicate otherwise good documentation\. Feynman covered all of physics \-\- heavenly bodies through QED \-\- with only two levels of document hierarchy (\fIThe Feynman Lectures on Physics\fR, 1970)\.
.
.IP "\(bu" 4
Man pages have a simple referencing syntax; e\.g\., sh(1), fork(2), markdown(7)\. HTML versions can use this to generate links between pages\.
.
.IP "\(bu" 4
The classical terminal man page display is typographically well thought out\. Big bold section headings, justified monospace text, nicely indented paragraphs, intelligently aligned definition lists, and an informational header and footer\.
.
.IP "" 0
.
.P
Unfortunately, figuring out how to create a manpage is a fairly tedious process\. The roff/man macro languages are highly extensible, fractured between multiple dialects, and include a bunch of device specific stuff irrelevant to modern publishing tools\.
.
.P
Ronn aims to address many of the issues with manpage creation while preserving the things that makes manpages a great form of documentation\.
.
.SH "COPYING"
Ronn is Copyright (C) 2009 Ryan Tomayko \fIhttp://tomayko\.com/about\fR
.
.br
See the file COPYING for information of licensing and distribution\.
.
.SH "SEE ALSO"
ronn(1) \fIhttp://rtomayko\.github\.com/ronn/ronn\.1\fR, ronn(5) \fIhttp://rtomayko\.github\.com/ronn/ronn\.5\fR, markdown(7)
