.\" generated with Ronn/v0.7.0
.\" http://github.com/rtomayko/ronn/tree/0.7.0
.
.TH "RONN" "1" "June 2010" "Ronn 0.7.0" "Ronn Manual"
.
.SH "NAME"
\fBronn\fR \- convert markdown files to manpages
.
.SH "SYNOPSIS"
\fBronn\fR [\fIformat\fR\.\.\.] \fIfile\fR\.\.\.
.
.br
\fBronn\fR \fB\-m\fR|\fB\-\-man\fR \fIfile\fR\.\.\.
.
.br
\fBronn\fR \fB\-S\fR|\fB\-\-server\fR \fIfile\fR\.\.\.
.
.br
\fBronn\fR \fB\-\-pipe\fR \fIfile\fR
.
.br
\fBronn\fR < \fIfile\fR
.
.SH "DESCRIPTION"
\fBRonn\fR converts textfiles to standard roff\-formatted UNIX manpages or HTML\. ronn\-format(7) is based on markdown(7) but includes additional rules and syntax geared toward authoring manuals\.
.
.P
In its default mode, \fBronn\fR converts one or more input \fIfile\fRs to HTML or roff output files\. The \fB\-\-roff\fR, \fB\-\-html\fR, and \fB\-\-fragment\fR options dictate which output files are generated\. Multiple format arguments may be specified to generate multiple output files\. Output files are named after and written to the same directory as input \fIfile\fRs\.
.
.P
The \fB\-\-server\fR and \fB\-\-man\fR options change the output behavior from file generation to serving dynamically generated HTML manpages or viewing \fIfile\fR as with man(1)\.
.
.P
With no \fIfile\fR arguments, \fBronn\fR acts as simple filter\. Ronn source text is read from standard input and roff output is written to standard output\. Use the \fB\-\-html\fR, \fB\-\-roff\fR, and/or \fB\-\-fragment\fR options to select the output format\.
.
.SH "FILES"
The \fBronn\fR command expects input to be valid ronn\-format(7) text\. Source files are typically named \fIname\fR\.\fIsection\fR\.ronn (e\.g\., \fBexample\.1\.ronn\fR)\. The \fIname\fR and \fIsection\fR should match the name and section defined in the \fIfile\fR\'s heading\.
.
.P
When building roff or HTML output files, destination filenames are determined by taking the basename of the input \fIfile\fR and adding the appropriate file extension (or removing the file extension in the case of roff output)\. For example, executing \fBronn example\.1\.ronn\fR generates \fBexample\.1\fR with roff output and \fBexample\.1\.html\fR with HTML output\.
.
.SH "OPTIONS"
These options control whether output is written to file(s), standard output, or directly to a man pager\.
.
.TP
\fB\-m\fR, \fB\-\-man\fR
Don\'t generate files, display \fIfile\fRs as if man(1) were invoked on the roff output file\. This simulates default man behavior by piping the roff output through groff(1) and the paging program specified by the \fBMANPAGER\fR environment variable\.
.
.TP
\fB\-S\fR, \fB\-\-server\fR
Don\'t generate files, start an HTTP server at \fIhttp://localhost:1207/\fR and serve dynamically generated HTML for the set of input \fIfile\fRs\. A file named \fIexample\.2\.ronn\fR is served as \fI/example\.2\.html\fR\. There\'s also an index page at the root with links to each \fIfile\fR\.
.
.IP
The server respects the \fB\-\-style\fR and document attribute options (\fB\-\-manual\fR, \fB\-\-date\fR, etc\.)\. These same options can be varied at request time by giving them as query parameters: \fB?manual=FOO&style=dark,toc\fR
.
.IP
\fINOTE: The builtin server is designed to assist in the process of writing and styling manuals\. It is in no way recommended as a general purpose web server\.\fR
.
.TP
\fB\-\-pipe\fR
Don\'t generate files, write generated output to standard output\. This is the default behavior when ronn source text is piped in on standard input and no \fIfile\fR arguments are provided\.
.
.P
Format options control the files \fBronn\fR generates, or the output format when the \fB\-\-pipe\fR argument is specified\. When no format options are given, both \fB\-\-roff\fR and \fB\-\-html\fR are assumed\.
.
.TP
\fB\-r\fR, \fB\-\-roff\fR
Generate roff output\. This is the default behavior when no \fIfile\fRs are given and ronn source text is read from standard input\.
.
.TP
\fB\-5\fR, \fB\-\-html\fR
Generate output in HTML format\.
.
.TP
\fB\-f\fR, \fB\-\-fragment\fR
Generate output in HTML format but only the document fragment, not the header, title, or footer\.
.
.P
Document attributes displayed in the header and footer areas of generated content are specified with these options\. (These values may also be set via the \fIENVIRONMENT\fR\.)
.
.TP
\fB\-\-manual\fR=\fImanual\fR
The name of the manual this man page belongs to; \fImanual\fR is prominently displayed top\-center in the header area\.
.
.TP
\fB\-\-organization\fR=\fIname\fR
The name of the group, organization, or individual responsible for publishing the document; \fIname\fR is displayed in the bottom\-left footer area\.
.
.TP
\fB\-\-date\fR=\fIdate\fR
The document\'s published date; \fIdate\fR must be formatted \fBYYYY\-MM\-DD\fR and is displayed in the bottom\-center footer area\. The \fIfile\fR mtime is used when no \fIdate\fR is given, or the current time when no \fIfile\fR is available\.
.
.P
HTML output can be customized through the use of CSS stylesheets:
.
.TP
\fB\-\-style\fR=\fImodule\fR[,\fImodule\fR]\.\.\.
The list of CSS stylesheets to apply to the document\. Multiple \fImodule\fR arguments may be specified, but must be separated by commas or spaces\.
.
.IP
When \fImodule\fR is a simple word, search for files named \fImodule\fR\fB\.css\fR in all directories listed in the \fI\fBRONN_STYLE\fR\fR environment variable, and then search internal styles\.
.
.IP
When \fImodule\fR includes a \fI/\fR character, use it as the full path to a stylesheet file\.
.
.IP
Internal styles are \fIman\fR (included by default), \fItoc\fR, and \fI80c\fR\. See \fISTYLES\fR for descriptions of features added by each module\.
.
.P
Miscellaneous options:
.
.TP
\fB\-w\fR, \fB\-\-warnings\fR
Show troff warnings on standard error when performing roff conversion\. Warnings are most often the result of a bug in ronn\'s HTML to roff conversion logic\.
.
.TP
\fB\-W\fR
Disable troff warnings\. Warnings are disabled by default\. This option can be used to revert the effect of a previous \fB\-w\fR argument\.
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Show ronn version and exit\.
.
.SH "LINK INDEXES"
When generating HTML output, \fBronn\fR hyperlinks manual references (like \fBgrep(1)\fR, \fBls(1)\fR, \fBmarkdown(7)\fR) in source text based on reference name to URL mappings defined in an \fBindex\.txt\fR file\. Each line of the index file describes a single reference link, with whitespace separating the reference\'s \fIid\fR from its \fIlocation\fR\. Blank lines are allowed; lines beginning with a \fB#\fR character are ignored:
.
.IP "" 4
.
.nf

# manuals included in this project:
whisky(1)    whisky\.1\.ronn
tango(5)     tango\.5\.ronn

# external manuals
grep(1)      http://man\.cx/grep(1)
ls(1)        http://man\.cx/ls(1)

# other URLs for use with markdown reference links
src          http://github\.com/
.
.fi
.
.IP "" 0
.
.P
The \fIlocation\fR is an absolute or relative URL that usually points at an HTML version of manpage\. It\'s possible to define references for things that aren\'t manpages\.
.
.P
All manuals in an individual directory share the references defined in that directory\'s \fBindex\.txt\fR file\. Index references may be used explicitly in Markdown reference style links using the syntax: \fB[\fR\fItext\fR\fB][\fR\fIid\fR\fB]\fR, where \fItext\fR is the link text and \fIid\fR is a reference name defined in the index\.
.
.SH "STYLES"
The \fB\-\-style\fR option selects a list of CSS stylesheets to include in the generated HTML\. Styles are applied in the order defined, so each can use the cascade to override previously defined styles\.
.
.SS "Builtin Stylesheets"
These styles are included with the distribution:
.
.TP
\fBman\fR
Basic manpage styles: typography, definition lists, indentation\. This is always included regardless of \fB\-\-style\fR argument\. It is however possible to replace the default \fBman\fR module with a custom one by placing a \fBman\.css\fR file on the \fBRONN_STYLE\fR path\.
.
.TP
\fBprint\fR
Basic print stylesheet\. The generated \fB<style>\fR tag includes a \fBmedia=print\fR attribute\.
.
.TP
\fBtoc\fR
Enables the Table of Contents navigation\. The TOC markup is included in generated HTML by default but hidden with an inline \fBdisplay:none\fR style rule; the \fBtoc\fR module turns it on and applies basic TOC styles\.
.
.TP
\fBdark\fR
Light text on a dark background\.
.
.TP
\fB80c\fR
Changes the display width to mimic the display of a classic 80 character terminal\. The default display width causes lines to wrap at a gratuitous 100 characters\.
.
.SS "Custom Stylesheets"
Writing custom stylesheets is straight\-forward\. The following core selectors allow targeting all generated elements:
.
.TP
\fB\.mp\fR
The manual page container element\. Present on full documents and document fragments\.
.
.TP
\fBbody#manpage\fR
Signifies that the page was fully\-generated by Ronn and contains a single manual page (\fB\.mp\fR element)\.
.
.TP
\fB\.man\-decor\fR
The three\-item heading and footing elements both have this class\.
.
.TP
\fB\.man\-head\fR, \fB\.man\-foot\fR
The heading and footing, respectively\.
.
.TP
\fB\.man\-title\fR
The main \fB<h1>\fR element\. Hidden by default unless the manual has no \fIname\fR or \fIsection\fR attributes\.
.
.P
See the builtin style sources \fIhttp://github\.com/rtomayko/ronn/tree/master/lib/ronn/template\fR for examples\.
.
.SH "EXAMPLES"
Build roff and HTML output files and view the roff manpage using man(1):
.
.IP "" 4
.
.nf

$ ronn some\-great\-program\.1\.ronn
roff: some\-great\-program\.1
html: some\-great\-program\.1\.html
$ man \./some\-great\-program\.1
.
.fi
.
.IP "" 0
.
.P
Build only the roff manpage for all \fB\.ronn\fR files in the current directory:
.
.IP "" 4
.
.nf

$ ronn \-\-roff *\.ronn
roff: mv\.1
roff: ls\.1
roff: cd\.1
roff: sh\.1
.
.fi
.
.IP "" 0
.
.P
Build only the HTML manpage for a few files and apply the \fBdark\fR and \fBtoc\fR stylesheets:
.
.IP "" 4
.
.nf

$ ronn \-\-html \-\-style=dark,toc mv\.1\.ronn ls\.1\.ronn
html: mv\.1\.html
html: ls\.1\.html
.
.fi
.
.IP "" 0
.
.P
Generate roff output on standard output and write to file:
.
.IP "" 4
.
.nf

$ ronn <hello\.1\.ronn >hello\.1
.
.fi
.
.IP "" 0
.
.P
View a ronn file in the same way as man(1) without building a roff file:
.
.IP "" 4
.
.nf

$ ronn \-\-man hello\.1\.ronn
.
.fi
.
.IP "" 0
.
.P
Serve HTML manpages at \fIhttp://localhost:1207/\fR for all \fB*\.ronn\fR files under a \fBman/\fR directory:
.
.IP "" 4
.
.nf

$ ronn \-\-server man/*\.ronn
$ open http://localhost:1207/
.
.fi
.
.IP "" 0
.
.SH "ENVIRONMENT"
.
.TP
\fBRONN_MANUAL\fR
A default manual name to be displayed in the top\-center header area\. The \fB\-\-manual\fR option takes precedence over this value\.
.
.TP
\fBRONN_ORGANIZATION\fR
The default manual publishing group, organization, or individual to be displayed in the bottom\-left footer area\. The \fB\-\-organization\fR option takes precedence over this value\.
.
.TP
\fBRONN_DATE\fR
The default manual date in \fBYYYY\-MM\-DD\fR format\. Displayed in the bottom\-center footer area\. The \fB\-\-date\fR option takes precedence over this value\.
.
.TP
\fBRONN_STYLE\fR
A \fBPATH\fR\-style list of directories to check for stylesheets given to the \fB\-\-style\fR option\. Directories are separated by a \fI:\fR; blank entries are ignored\. Use \fI\.\fR to include the current working directory\.
.
.TP
\fBMANPAGER\fR
The paging program used for man pages\. This is typically set to something like \'less \-is\'\.
.
.TP
\fBPAGER\fR
Used instead of \fBMANPAGER\fR when \fBMANPAGER\fR is not defined\.
.
.SH "BUGS"
\fBRonn\fR is written in Ruby and depends on hpricot and rdiscount, extension libraries that are non\-trivial to install on some systems\. A more portable version of this program would be welcome\.
.
.SH "COPYRIGHT"
Ronn is Copyright (C) 2009 Ryan Tomayko \fIhttp://tomayko\.com/about\fR
.
.SH "SEE ALSO"
ronn\-format(7), manpages(5), man(1), roff(7), groff(1), markdown(7)
