.TH "DEFITION_LIST_SYNTAX" "5" "January 1979" "" ""
.
.SH "NAME"
\fBdefition_list_syntax\fR \- hiya
.
.P
Definition lists look like unordered lists:
.
.TP
term
definition
.
.TP
another one
The definition may span multiple lines and even
.
.IP
start
.
.IP
new paragraphs
.
.TP
\fB\-\-somearg\fR=\fIVALUE\fR
We can do that too\.

