.TH "DOTS_AT_LINE_START_TEST" "" "January 1979" "" ""
.
.SH "NAME"
\fBdots_at_line_start_test\fR
.
.P
There\'s a weird issue where dots at the beginning of a line generate troff warnings due to escaping.
.
.P
\&.. let\'s see what happens.
.
.IP "" 4
.
.nf

\&. This dot is escaped correctly.

a test
b test
\&. This one is too.
.
.fi
.
.IP "" 0
.
.P
\&.
.
.P
(Single dots should get replaced correctly, too.)
