.TH "HELLO" "1" "January 1979" "" ""
.
.SH "NAME"
\fBhello\fR \- hello world
.
.P
Your output <i>might</i> look like this:
.
.IP "" 4
.
.nf

* Chris
*
* &lt;b&gt;GitHub&lt;/b&gt;
* <b>GitHub</b>
.
.fi
.
.IP "" 0
.
.P
Here\'s some special entities:
.
.IP "\(bu" 4
&bull; \(bu
.
.IP "\(bu" 4
&nbsp; \~
.
.IP "\(bu" 4
&copy; \(co
.
.IP "\(bu" 4
&rdquo; \(rs
.
.IP "\(bu" 4
&mdash; \(em
.
.IP "\(bu" 4
&reg; \(rg
.
.IP "\(bu" 4
&sec; \(sc
.
.IP "\(bu" 4
&ge; \(>=
.
.IP "\(bu" 4
&le; \(<=
.
.IP "\(bu" 4
&ne; \(!=
.
.IP "\(bu" 4
&equiv; \(==
.
.IP "" 0
.
.P
Here\'s a line that uses non\-breaking spaces to force the last\~few\~words\~to\~wrap\~together\.
