.\" generated with Ronn/v0.6.0
.\" http://github.com/rtomayko/ronn/
.
.TH "MISSING_SPACES" "" "January 1979" "" ""
\.\\\" generated with Ronn/v0\.6\.0 \.\\\" http://github\.com/rtomayko/ronn/ \. \.TH \"MISSING_SPACES\" \"\" \"June 2010\" \"\" \"\" \. \.TP \\fB\-S \\fR\\fItext\\fR, \\fBsearch \\fR\\fItext\\fR Performs a substring search of formula names for \\fItext\\fR\.
