.TH "UNDERLINE_SPACING_TEST" "" "January 1979" "" ""
.
.SH "NAME"
\fBunderline_spacing_test\fR
.
.P
This input
.
.TP
\fB\-S\fR \fItext\fR, \fBsearch\fR \fItext\fR
Performs a substring search of formula names for \fItext\fR\.
.
.TP
\fB\-O\fR \fItext\fR, \fBother\fR \fItext\fR
Does something else\.
.
.P
Should space text properly\.
.
.P
\fI!\-\- this is a comment \-\-\fR
