#!/usr/bin/env ruby

begin
  require 'rdiscount'
rescue LoadError
  require 'rubygems'
  require 'rdiscount'
end

require 'nokogiri'

def process_definition_lists(html)
  doc = Nokogiri::HTML(html)
  doc.xpath('//ul').each do |ul|
    items = ul.xpath('li')
    next if items.any? { |item| item.text.split("\n", 2).first !~ /:$/ }

    ul.name = 'dl'
    items.each do |item|
      if item.child.name == 'p'
        para = item.child
        term, definition = para.inner_html.split(":\n", 2)
        item.before("<dt>#{term}</dt>")
        dt = item.previous_sibling
        dt['class'] = 'flush' if dt.content.length <= 10
        item.name = 'dd'
        para.inner_html = definition
      else
        term, definition = item.inner_html.split(":\n", 2)
        item.before("<dt>#{term}</dt>")
        dt = item.previous_sibling
        dt['class'] = 'flush' if dt.content.length <= 8
        item.name = 'dd'
        item.inner_html = definition
      end
    end
  end
  doc.to_s
end

ARGV.each do |filename|
  basename = File.basename(filename)
  name, section =
    if basename =~ /(\w+)\.(\d\w*)\.mad$/
      [$1, $2]
    else
      [basename[/\w+/], nil]
    end
  input = File.read(filename)
  html = Markdown.new(input).to_html
  title, html = html.split("</h1>\n", 2)
  title.sub!('<h1>', '')

  html = process_definition_lists(html)

  output = eval("%Q{#{DATA.read}}")
  $stdout.write(output)
end

__END__
<!DOCTYPE html>
<html>
<head>
  <title>#{name}(#{section}) - #{title}</title>
  <style type='text/css'>
  body { font-family:consolas,monospace;font-size:18px;line-height:1.25;color:#333 }
  #man { max-width:42em;text-align:justify }
  h1, h2, h3, strong, code { color:#111 }
  h1 { text-align:center }
  h2 { font-size:20px;margin-bottom:0 }
  h3 { font-size:18px;margin:0 0 0 50px }
  p, ul, ol, dl, pre { margin:0 0 24px 0; }
  #man > p, #man > ul, #man > ol, #man > dl, #man > pre { margin:0 0 24px 80px; }
  dt { margin:0;clear:left }
  dt.flush { float:left;width:105px }
  dd { margin:0 0 24px 105px }
  code { font-weight:bold; }
  pre code { font-weight:normal; }
  em { font-style:normal;text-decoration:underline }

  </style>
</head>
<body>
<div id='man'>

<h1>#{name}(#{section})</h1>

<h2>NAME</h2>
<p><code>#{name}</code> - #{title}</p>

#{html}

</div>
</body>
</html>
